name: Build and Release Binary

on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Release
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.6' # The Go version to download (if necessary) and use
      - run: go build -ldflags -H=windowsgui
